### ISSUE TITLE
MAX31856 Thermocouple Amplifier does not align to grid

### ISSUE THREAD

**Issue by RandScullard** [adafruit/Fritzing-Library#102]
The connectors on the MAX31856 Thermocouple Amplifier do not align to the Fritzing grid. I need to turn off `View: Align to Grid` to align this component with my breadboard connections.

**Comment by ladyada** [comment]
not surprising, the grid is hard to 'fix' - we find even the same parts, depending on the order we put them in the BB can go out of grid
plz continue to turn off align-to-grid - thx!
