### ISSUE TITLE
Perma-Proto 1/4 Board missing from Library but in Parts folder

### ISSUE THREAD

**Issue by jaseiffert** [adafruit/Fritzing-Library#105]
I found this board in the parts PermaprotoQuarterBoard.fzpz but it isn't in the Adafruit.fzbz library or what ever it's called. Also in the Parts folder the description I guess it is says 1/2 board.

I've imported it manually but wanted to let you know.

Thanks,

Jeffery

**Comment by ladyada** [comment]
ok!
