### ISSUE TITLE
Flora Bluetooth LE Module missing

### ISSUE THREAD

**Issue by rogeriobiondi** [adafruit/Fritzing-Library#106]
Hello,

I'm trying to sketch my project in fritzing but some FLORA modules such as Bluetooth LE and GPS are missing in Adafruit Fritzing Library.  

https://learn.adafruit.com/adafruit-flora-bluefruit-le/overview?view=all

May you provide them, please, or point a replacement part?

Best regards,
Rogério

**Comment by ladyada** [comment]
Its in the Adafruit bin search for FLORA

**Comment by rogeriobiondi** [comment]
Hello,

Just found it. Thank you very much and sorry. I was looking for them on the retired folder. :o)

Best regards,
Rogerio
