### ISSUE TITLE
ESP32 feather component is missing TX/RX pins

### ISSUE THREAD

**Issue by rtwfroody** [adafruit/Fritzing-Library#108]

**Comment by ladyada** [comment]
they are there - labeled IO16 and IO17
thx!

**Comment by rtwfroody** [comment]
Thank you! I just realized that the bottom of the board has that labelled as well. I was reading https://learn.adafruit.com/adafruit-huzzah32-esp32-feather/pinouts which does not mention that they are also IO pins (although I should have guessed).

I love your hardware. Thank you.
