### ISSUE TITLE
Parts Request: Adafruit HUZZAH32 - ESP32 Feather

### ISSUE THREAD

**Issue by lwoodbury** [adafruit/Fritzing-Library#111]
[https://learn.adafruit.com/adafruit-huzzah32-esp32-feather/overview]

Thank You!

**Comment by ladyada** [comment]
![image](https://user-images.githubusercontent.com/1214161/34843666-17c41e84-f6dd-11e7-8758-8814c775fe3b.png)

hiya its already there!

**Comment by lwoodbury** [comment]
Ah!! OK, thank you, it hasn't made it into the feather bin and I was looking for it in the wrong place.
