### ISSUE TITLE
request for adafruit motor shield v2.3 fritzing

### ISSUE THREAD

**Issue by bgannon29** [adafruit/Fritzing-Library#116]
the latest adafruit frtizing library doesnt contain the motor shield v2.3 

there is another post where ladyada posted a fritzing picture but no link to the bin files

**Comment by ladyada** [comment]
this isnt it?
https://github.com/adafruit/Fritzing-Library/blob/master/parts/Adafruit%20Motor%2C%20Stepper%20%26%20Servo%20Shield.fzpz
