### ISSUE TITLE
Add the Waveshield

### ISSUE THREAD

**Issue by bberg** [adafruit/Fritzing-Library#12]
Please add the Waveshield to this excellent library.

http://www.adafruit.com/products/94

**Comment by Levi-Lesches** [comment]
Why was this closed?

**Comment by ladyada** [comment]
dunno - was a long time ago :D is the waveshield in the parts folder?

**Comment by Levi-Lesches** [comment]
Nope

**Comment by ladyada** [comment]
looks like there's an issue here
https://github.com/adafruit/Fritzing-Library/issues/91
no ETA but you can subscribe and when we do it, well close that issue

**Comment by Levi-Lesches** [comment]
OK, thanks
