### ISSUE TITLE
Part Request: pid 3309: Adafruit CP2104 Friend - USB to Serial Converter

### ISSUE THREAD

**Issue by evanroode** [adafruit/Fritzing-Library#149]
It is an old part, so probably low priority. Admittedly I probably will just do my breadboard on paper but having the part in the library my be useful for other people

https://www.adafruit.com/product/3309

As far as I can tell it is not in the repo, and I don't have Eagle (I did have a look at the eagle2fritzing in the learn system)

**Comment by kattni** [comment]
@evanroode Part added! https://github.com/adafruit/Fritzing-Library/blob/master/parts/Adafruit%20CP2104%20Friend.fzpz
