### ISSUE TITLE
Part Request: Adafruit Feather M0 WiFi with uFL - ATSAMD21 + ATWINC1500 - fw 19.4.4

### ISSUE THREAD

**Issue by awatterson22** [adafruit/Fritzing-Library#156]
Hi! I was wondering if it would be possible to create a fritzing schematic for this part. I am trying to create a schematic for my honors thesis. Thank you!

**Comment by ladyada** [comment]
![image](https://user-images.githubusercontent.com/1214161/156659999-6f065c81-53a0-4cfa-8cae-393cdc8efded.png)

trythis
