### ISSUE TITLE
1.8" TFT Shield V2

### ISSUE THREAD

**Issue by JonathahGear** [adafruit/Fritzing-Library#162]
Sorry if this is already available, but is it possible to get a Fritzing file for the 1.8" TFT Shield V2?

https://learn.adafruit.com/1-8-tft-display/1-8-tft-shield

thank you

**Comment by ladyada** [comment]
@kattni take a look if it already exists first! :)

**Comment by kattni** [comment]
We did not create a Fritzing object for Revision B of the 1.8" TFT Shield. I will add it to my list to create it, and I will reply here with a link when it is completed.

**Comment by kattni** [comment]
Passing this onto @BlitzCityDIY for completion.

**Comment by JonathahGear** [comment]
Thank you so much everyone!!
