### ISSUE TITLE
No PCB layout for Neopixel Flora

### ISSUE THREAD

**Issue by tguidon** [adafruit/Fritzing-Library#17]
I am trying to incorporate the Flora into a PCB board I am designing and it won't let me add this to my board. It looks like it is not included. Is this in development or impossible due to lack of datasheets? Thanks.

**Comment by SoyTecnopata** [comment]
I have the same issue. I need the flora or mini version!

**Comment by dhalbert** [comment]
I imported https://github.com/adafruit/Fritzing-Library/blob/master/parts/Adafruit%20Flora%20v3.fzpz into fritzing, and see only the board connections, not the whole layout, but I'm not very familiar with fritizing. Did you try that file? However, the Eagle files that were actually used to make the board are available: https://github.com/adafruit/Adafruit-Flora-Mainboard. There are converters from Eagle to fritzing, or you could design the board in Eagle (or kicad, which can import Eagle).
