### ISSUE TITLE
Request for Motor Shield v2.0

### ISSUE THREAD

**Issue by NanoDevEU** [adafruit/Fritzing-Library#20]
Could you add the Adafruit Motor Shield v2.0 to the libary ?

**Comment by entomophile** [comment]
Add me to the list, could really use that file.

**Comment by nonkreon** [comment]
v2.3 would also be good

**Comment by wcndave** [comment]
I'd love to see this too!

**Comment by ladyada** [comment]
![mshield](https://cloud.githubusercontent.com/assets/1214161/16848846/bdb7fef8-49c5-11e6-9f1c-c99bfc9a96c9.png)

done!

**Comment by bgannon29** [comment]
where is the file.....it is not in adafruits fritzing libray on github
