### ISSUE TITLE
Neopixel Strip's connector names are not correct

### ISSUE THREAD

**Issue by mactkg** [adafruit/Fritzing-Library#22]
![e848493a02d053c48b5aa77971f8434a](https://f.cloud.github.com/assets/178418/1961045/add9d374-8264-11e3-831f-34a6e7ce5a62.gif)
'DIN(DI)' connector and '5V' connector are changed.

![2a67aa612b98ddaa69332b191476dc95](https://f.cloud.github.com/assets/178418/1961073/6e120760-8265-11e3-80ab-befd7d5b43df.gif)
'DO' connector and '5V' connector also changed.

**Comment by ejalaa12** [comment]
+1 I confirm I have the same issue with the 60/m version. (*the schematics are correct however*)

**Comment by ladyada** [comment]
fixed!
