### ISSUE TITLE
MCP23017 VDD/VSS mistake on screen PCB

### ISSUE THREAD

**Issue by grijon** [adafruit/Fritzing-Library#26]
I have found the VDD/VSS mistake in part mcp23017 on screen PCB.
VDD and VSS uses same pin 9.

I have fixed it and you could find fixed file of the MCP23017 part at
https://github.com/grijon/RPI-projects/blob/master/Fritzing%20Parts/mcp23017_fixed.fzpz

**Comment by ladyada** [comment]
i think this was fixed and not closed, so closing!
