### ISSUE TITLE
Request for Beaglebone Proto cape

### ISSUE THREAD

**Issue by pjz** [adafruit/Fritzing-Library#27]
http://www.adafruit.com/products/572

**Comment by chuyskywalker** [comment]
I, too, was looking for this one.

**Comment by schallee** [comment]
I too would really appreciate this. I am totally new to fritzing and have no idea how to make a proper part for it but attached is at least something.



[proto_cape_attempt.fzz.zip](https://github.com/adafruit/Fritzing-Library/files/145053/proto_cape_attempt.fzz.zip)

**Comment by ladyada** [comment]
done!
