### ISSUE TITLE
Protoboard is on the 'parts' layer, not breadboard layer.

### ISSUE THREAD

**Issue by ascorbic** [adafruit/Fritzing-Library#32]
The Protoboard should be on the 'breadboard' layer in Breadboard view, which would mean it would display below parts. This can't be done directly in the editor, but can be done by manually editing the fzp file to change the layer from "breadboard" to "breadboardbreadboard".

**Comment by MicaSbg** [comment]
Where exactly can I find this fzp file after I installed the Adafruit libary? I did a search, but can't locate it. I found other fzp files, from Sparkfun for example, but the Adafruit are nowhere to be found. In my fritzing all hte Adafruit parts show up, but I'm still having the issue of the board being on the wrong layer.

**Comment by ladyada** [comment]
ascorbic, unclear if this is necessary, can you just Move To Bottom or is this a special thing?
