### ISSUE TITLE
Request for Permaproto for Raspi

### ISSUE THREAD

**Issue by snrkl** [adafruit/Fritzing-Library#36]
It would be great to have both the ADAFRUIT PERMA-PROTO RASPBERRY PI BREADBOARD PCB KIT and the ADAFRUIT HALF-SIZE PERMA-PROTO RASPBERRY PI BREADBOARD PCB KIT as icons for Fritzing - I have been using the permaproto and the piCobbler, but there is not much room after you stack them together to easily plan a tight layout for the GPIO pins..

products: http://www.adafruit.com/products/1135 and http://www.adafruit.com/products/1148 are the ones I am after...

**Comment by ladyada** [comment]
done!
