### ISSUE TITLE
add license file

### ISSUE THREAD

**Issue by matt-cook** [adafruit/Fritzing-Library#40]
Thanks for the great library! We've created a modified version of one of the components and need to know specifically what license it should be released under? https://github.com/zebradog/fritzing-pololu-led-60

>  we enthusiastically encourage you to learn from, modify and re-share our Fritzing library

... is fantastic, but not 100% clear.

**Comment by tamberg** [comment]
+1. If possible, CC BY-SA would be great, for compatibility with Fritzing.org (http://fritzing.org/faq/).

**Comment by ladyada** [comment]
done!
