### ISSUE TITLE
Request for 12-Key Capacitive Touch Sensor Breakout - MPR121 part

### ISSUE THREAD

**Issue by dbeusink** [adafruit/Fritzing-Library#43]
Dear Adafruit team,

I would be very thankful if you could make the "12-Key Capacitive Touch Sensor Breakout - MPR121"  part for me.

Regards,

Daan

http://www.adafruit.com/products/1982

**Comment by haleyrowland** [comment]
+1

**Comment by firmread** [comment]
+1

**Comment by 20oskar00** [comment]
+1

**Comment by ladyada** [comment]
https://github.com/adafruit/Fritzing-Library/commit/edcaf3eba518dc1a7fdb2c99eed1a0611a2940a7

happy birthday!
