### ISSUE TITLE
T Cobbler Plus pins are mislabeled/wrong

### ISSUE THREAD

**Issue by nkolban** [adafruit/Fritzing-Library#46]
Using the latest Fritzing parts I find that the T-Cobbler Plus pins are mislabeled.  To see this, open up the T-Cobbler Plus and open the parts editor.  Select the pin labeled on the board as "#20" and see that it is actually flagged as GND.  There are many other pins mislabeled.  The board image is correct but the connector list is wrong.

See attached screen shot for an example.

![2015-03-30_17-31-12](https://cloud.githubusercontent.com/assets/3421732/6908441/b250ce6e-d702-11e4-8ab6-370953f25037.png)

**Comment by nkolban** [comment]
Am I able to make the changes myself to this Github project and check-in the changes?  I don't want to waste time fixing things if I don't have permissions to check changes back in.

**Comment by matt-cook** [comment]
@nkolban you'll want to make a fork of the repository into your own account, push the changes to that and then create a pull request: https://help.github.com/articles/using-pull-requests/

**Comment by ladyada** [comment]
they've all been redone!
