### ISSUE TITLE
Pi cobblers don't produce reliable ratsnest in PCB

### ISSUE THREAD

**Issue by patrickfuller** [adafruit/Fritzing-Library#47]
As an example, if you set up this breadboard:

![bb](https://cloud.githubusercontent.com/assets/1449833/8443238/a5f73942-1f4a-11e5-982a-1a593e520175.png)

the PCB ratsnest connects two unrelated pins:

![screenshot from 2015-06-30 17 07 07](https://cloud.githubusercontent.com/assets/1449833/8443244/b10241f6-1f4a-11e5-8b90-a9b61e28ef02.png)

**Comment by nkolban** [comment]
Howdy Patrick, see also issue #46 I get the feeling that there is no-one on duty watching these issues.  You might want to modify the Fritizing parts yourself if you are in a hurry.

**Comment by patrickfuller** [comment]
If no one's watching these issues, then that sounds like the best way to go.

I would still like to make sure that the Pi cobbler works for everyone. I'll send an email and see if I have any luck.

**Comment by patrickfuller** [comment]
Posted this on [adafruit's forum](https://forums.adafruit.com/viewtopic.php?f=50&t=76186&p=386486#p386486). Hopefully this gets resolved.

**Comment by nkolban** [comment]
Good idea.  Wish I'd thought to do that myself with the issue I raised ... I just sat here mumbling that Adafruit weren't watching the issues :-)

**Comment by ladyada** [comment]
they've all been redone!
