### ISSUE TITLE
Do these files work with 7.11?

### ISSUE THREAD

**Issue by alecthegeek** [adafruit/Fritzing-Library#5]
I've installed Fritsing 7.11 and it will not import these fzpz files.

"Unable to open shareable part"

Is it an issue with version compatibility?

**Comment by solidcloudio** [comment]
When you download individual files from github, windows "blocks" the files.  When you check -out the repo of download as a .zip, the files are blocked.  You can right-click each file and choose un-block

**Comment by Anton-Ka** [comment]
> When you download individual files from github, windows "blocks" the files. When you check -out the repo of download as a .zip, the files are blocked. You can right-click each file and choose un-block

HI.
I am also getting a warning. Can you suggest how to fix this?
![image](https://user-images.githubusercontent.com/74901464/165745558-ab657350-6fca-4e4a-b628-3d084ef40f98.png)
I have not opened the program for a long time, but then everything worked. I could add components via "drag and drop" and via "File - Open".
