### ISSUE TITLE
Add adafruit proto shield (newest version R3) please

### ISSUE THREAD

**Issue by liudr** [adafruit/Fritzing-Library#53]
This shield is pretty good for prototyping especially after you added the ICSP header. I imagine that many will be interested in documenting how they use it to wire up things. Be nice to have a fritzing part for it. Thanks.

https://www.adafruit.com/product/2077

**Comment by mangtronix** [comment]
There's a user contributed one here https://forums.adafruit.com/viewtopic.php?f=31&t=36560#p254041

**Comment by ladyada** [comment]
added but be aware the schematic view is not working - its for diagramming only
