### ISSUE TITLE
Part Request : Adafruit BMP280 and Adafruit BMP180

### ISSUE THREAD

**Issue by thegounet** [adafruit/Fritzing-Library#57]
May be interting to add Adafruit BMP280 and Adafruit BMP180 in your library 

Thank in advance.

**Comment by ladyada** [comment]
https://github.com/adafruit/Fritzing-Library/commit/1a551969b4ad32612b319f729b36610c0a9803b9
https://github.com/adafruit/Fritzing-Library/commit/c2568bc777aaf30c13955fc547606cc15e2f96c2
happy holidays!
