### ISSUE TITLE
DS18b20 GND and VDD pin exchanged on graphic

### ISSUE THREAD

**Issue by angsuarez** [adafruit/Fritzing-Library#60]
The pins are named correctly : 1 for GND, 2 for Data and 3 for VDD, but the image on protoboard doesn't match the pin number for the ds18b20 sheet 

![ds18b20](https://cloud.githubusercontent.com/assets/7619660/12869974/25d4b224-cd2f-11e5-98db-d8ea8f434cc5.jpeg)

If you look the front (the flat face,) on the left is located the ground pin but the fritzing DS18B20 part has pin number 1 on the right side

**Comment by Lodimup** [comment]
Confirmed. They are incorrect.

**Comment by ladyada** [comment]
i just looked and its correct? maybe it was fixed since then? re-open if you can verify the current adafruit library is wrong plz :)
