### ISSUE TITLE
FeatherWing Proto?

### ISSUE THREAD

**Issue by schallee** [adafruit/Fritzing-Library#61]
It would be nice to have a part for the FeatherWing Proto: https://www.adafruit.com/products/2884

I'm slowly working on this (not knowing Fritizing or SVG well) but I have attached my work in progress breadboard SVG in case anyone else is interested so we don't duplicate work. If I get it all done I'll submit a pull request but at least it
[feather_wing_proto_breadboard.svg.zip](https://github.com/adafruit/Fritzing-Library/files/162465/feather_wing_proto_breadboard.svg.zip)

s something;)

**Comment by ladyada** [comment]
generated one added!
