### ISSUE TITLE
Part Request: ATXRaspi

### ISSUE THREAD

**Issue by lelandg** [adafruit/Fritzing-Library#62]
I would like to use this part in an OS project I have released, but I'm having problems creating it (with the new Fritzing). I'm not giving up, but someone here could probably knock this out in no time. Here's the URL for the part: 

https://lowpowerlab.com/shop/ATXRaspi-R2

There is a dimension diagram here:

http://lowpowerlab.com/atxraspi/#tab5

**Comment by ladyada** [comment]
we dont sell, support or own this component, you're best off talking to lowpowerlabs directly
