### ISSUE TITLE
Newpixel Jewel pins inconsistently named

### ISSUE THREAD

**Issue by sethmg** [adafruit/Fritzing-Library#66]
The pins in the file

https://github.com/adafruit/Fritzing-Library/blob/master/parts/NeoJewel.fzpz

are inconsistent. The pin labelled IN on the breadboard view is labelled DATA OUT on the schematic and vice versa.

**Comment by veggie2u** [comment]
Found that myself. If you switch the in/out in the part editor/connectors, it will work for you.

**Comment by ladyada** [comment]
https://github.com/adafruit/Fritzing-Library/commit/e6e0197e10122178846ebbee484fab80550325ab
fixed!
