### ISSUE TITLE
SHT31-D 

### ISSUE THREAD

**Issue by kentstroker** [adafruit/Fritzing-Library#70]
Be nice to have the SHT31-D included.  Also the breadboard ready Neopixels.

**Comment by ladyada** [comment]
sht31 done

**Comment by kentstroker** [comment]
Thank you, this will make the lab manuals I am making much better.  Teaching a hands-on workshop using the MKR1000 to a few hundred folks up and down the west coast as part of our IBM IoT Coot Camp educational series.  This was the one Adafuit sensor for the documentation I did not have, I was about to try the eagle2frtiz tool - thanks for posting this up.

-Kent

**Comment by ladyada** [comment]
yay thank you! we're doing 2-3 a day but in an 'arbitrary order' so request them if you want to get a particular :)
