### ISSUE TITLE
Part Request: RFM9X LoRa Packet Radio

### ISSUE THREAD

**Issue by DaveKT** [adafruit/Fritzing-Library#73]
I downloaded Adafruit Fritzing's library from Github and I'd like to request an addition to the repository, the RFM9X LoRa Packet Radio. (here: https://www.adafruit.com/products/3072)

Thank you for your consideration.

**Comment by kdombeck** [comment]
+1

**Comment by ladyada** [comment]
done!

**Comment by DaveKT** [comment]
Thanks!

**Comment by electrodummy** [comment]
+1
