### ISSUE TITLE
Adafruit 16x9 Charlieplexed PWM LED Matrix Driver - IS31FL3731

### ISSUE THREAD

**Issue by onebeartoe** [adafruit/Fritzing-Library#78]
Please provide a Fitzing part for this product.  It is great and I need it for project documentation.

https://www.adafruit.com/products/2946

(thank you)

**Comment by ladyada** [comment]
ok!

**Comment by onebeartoe** [comment]
Thanks again!

http://electronics.onebeartoe.org/IS31FL3731/audio-input/
