### ISSUE TITLE
SMT RGB 5050 LED (PRODUCT ID: 619)

### ISSUE THREAD

**Issue by k5map** [adafruit/Fritzing-Library#79]
Based on what I read on the Adafruit website, this part has been added to the Eagle library.  Would it be possible to get this part added to the Fritzing library as well?

**Comment by ladyada** [comment]
we're only doing the breadboardable parts at this time!

**Comment by R-OLE** [comment]
But Adafruit does sell a [breakout board](https://www.adafruit.com/product/1762) **specifically** for this part. 
Having the ability to model the assembled board it after mounting the LED is a reasonable request.

**Comment by ladyada** [comment]
ok you can open an issue for that part if ya like - its not the same as P619

**Comment by janedapain** [comment]
The smd part please
