### ISSUE TITLE
Part Request: USB / DC / Solar Lithium Ion/Polymer charger - v2

### ISSUE THREAD

**Issue by LoveBootCaptain** [adafruit/Fritzing-Library#83]
https://www.adafruit.com/products/390

Would be awesome to see this in one of the next updates. Need an exact plan for a pcb with outlines i want to design. 

kind regards

**Comment by ladyada** [comment]
added!

**Comment by LoveBootCaptain** [comment]
Thank you very very much @ladyada... Tuesday is fritzing day in Berlin :)
