### ISSUE TITLE
Part Request: VERTER 5V USB Buck-Boost - 500mA from 3V-5V / 1000ma from 5V-12V

### ISSUE THREAD

**Issue by LoveBootCaptain** [adafruit/Fritzing-Library#84]
https://www.adafruit.com/products/2190

Here is another part request for my solar powered huzzah weather data project.

kind regards from Berlin

**Comment by ladyada** [comment]
its already been done

**Comment by LoveBootCaptain** [comment]
Sorry for that... Found it, but it didn`t fit to the breadboard :(

2016-08-27 20:56 GMT+02:00 ladyada <notifications@github.com>:
