### ISSUE TITLE
Part Request: PowerBoost 1000C

### ISSUE THREAD

**Issue by chrisbalmer** [adafruit/Fritzing-Library#90]
The PowerBoost 1000 is in there, but not the charger model. The tutorial mentions that it is in there so maybe it is an oversight on my part. I'm just not seeing the charger model in the parts folder or in the combined bin.

**Comment by ladyada** [comment]
they're not in the bins yet but the individual parts have been added

**Comment by chrisbalmer** [comment]
Awesome, thanks!
