### ISSUE TITLE
Part request : SHT31 - Grove version

### ISSUE THREAD

**Issue by FROISSARTKevin** [adafruit/Fritzing-Library#92]
Hey, i wanted to know if their is a fritzing version of this sensor (Grove - Temperature&Humidity Sensor (SHT31) https://www.seeedstudio.com/Grove-Temperature%26amp%3BHumidity-Sensor-%28SHT31%29-p-2655.html ) I found result with the SHT31-D sensor, but that's not the one i need unfortunatly.

**Comment by ladyada** [comment]
plz ask seeed for asistance :)
