### ISSUE TITLE
Part Request: Mini Skinny NeoPixel Digital RGB LED Strip - 60 LED/m

### ISSUE THREAD

**Issue by sgilroy** [adafruit/Fritzing-Library#97]
The pin order (and pin labels) is different from the other NeoPixel strips.

Other strips:
DIN, +5V, GND

This strip:
+, D, -

https://www.adafruit.com/product/2964

Thanks! The parts (as usual) are great, and this Fritzing library is a huge asset for teaching and sharing ideas.

**Comment by ladyada** [comment]
strip pin ordering isnt guaranteed - even if its called the 'same' so we will keep just generic neopixel strips!
